package main

// TEST
var names = map[string][]string{
	"toneGeneratorMode": {
		"Sound mode",
		"Pianist mode",
	},
	"kbMode": {
		"Single",
		"Dual",
		"Split",
		"4Hands",
	},
	"renderingCharacter": {
		"Classic",
		"Romantic",
		"Full",
		"Jazz",
		"Brilliant",
		"Rich",
		"Ballad",
		"Pop",
		"Vintage",
		"Boogie",
	},
	"instrumentSound": {
		// Piano 1
		"SK ConcertGrand",
		"EX ConcertGrand",
		"SK-5 Grand",
		"Jazz Clean",
		"Jazz Old School",
		"Warm Grand",
		"Warm Grand 2",
		"Standard Grand",
		// Piano 2
		"Pop Grand",
		"Pop Grand 2",
		"Pop Piano",
		"New Age Grand",
		"Upright Piano",
		"Modern Piano",
		"Boogie Piano",
		"Honky Tonk",
		// Electric Piano
		"Classic Electric Piano",
		"60's Electric Piano",
		"Modern Electric Piano",
		"Classic Electric Piano 2",
		"Classic Electric Piano 3",
		"Crystal Electric Piano",
		"Modern Electric Piano 2",
		"Modern Electric Piano 3",
		// Organ
		"Jazz Organ",
		"Blues Organ",
		"Ballad Organ",
		"Gospel Organ",
		"Drawbar Organ",
		"Drawbar Organ 2",
		"Drawbar Organ 3",
		"Drawbar Organ 4",
		"Church Organ",
		"Diapason",
		"Full Ensemble",
		"Diapason Oct.",
		"Chiffy Tibia",
		"Principal Oct.",
		"Baroque",
		"Soft Diapasn",
		"Soft Strings",
		"Mellow Flutes",
		"Medium Ensemble",
		"Loud Ensembe",
		"Bright Ensemble",
		"Full Organ",
		"Reed Ensemble",
		// Harpsi & Mallets
		"Harpsichord",
		"Harpsichord Oct",
		"Vibraphone",
		"Clavi",
		"Marimba",
		"Celesta",
		"Harpsichord 2",
		"Bell Split",
		// Strings
		"Slow Strings",
		"String Pad",
		"Warm Strings",
		"String Ensemble",
		"Soft Orchestra",
		"Chamber Strings",
		"Harp",
		"Pizzicato Str.",
		// Vocal & Pad
		"Choir",
		"Pop Ooh",
		"Pop Aah",
		"Choir 2",
		"Jazz Ensemble",
		"Pop Ensemble",
		"Slow Choir",
		"Breathy Choir",
		"New Age Pad",
		"Atmosphere",
		"Itopia",
		"Brightness",
		"New Age Pad 2",
		"Brass Pad",
		"Bowed Pad",
		"Bright Warm Pad",
		// Bass & Guitar
		"Wood Bass",
		"Finger Bass",
		"Fretless Bass",
		"Principal Choir",
		"W.Bass & Ride",
		"E.Bass & Ride",
		"Ballad Guitar",
		"Pick Nylon Gt.",
		"Finger Nylon Gt",
	},
	"metronomeOnOff": {
		"Off",
		"On",
	},
	"rhythmPattern": {
		"1/4",
		"2/4",
		"3/4",
		"4/4",
		"5/4",
		"3/8",
		"6/8",
		"7/8",
		"9/8",
		"12/8",
		// 8 Beat
		"8 Beat 1",
		"8 Beat 2",
		"8 Beat 3",
		"Pop 1",
		"Pop 2",
		"Pop 3",
		"Pop 4",
		"Pop 5",
		"Pop 6",
		"Ride Beat 1",
		"Ride Beat 2",
		"Dance Pop 1",
		"Country Pop",
		"Smooth Beat",
		"Rim Beat",
		// 8 Beat Rock
		"Modern Rock 1",
		"Modern Rock 2",
		"Modern Rock 3",
		"Modern Rock 4",
		"Pop Rock",
		"Ride Rock",
		"Jazz Rock",
		"Surf Rock",
		// 16 Beat
		"16 Beat",
		"Indie Pop 1",
		"Acid Jazz 1",
		"Ride Beat 3",
		"Dance Pop 2",
		"Dance Pop 3",
		"Dance Pop 4",
		"Dance Pop 5",
		"Dance Pop 6",
		"Dance Pop 7",
		"Dance Pop 8",
		"Indie Pop 2",
		"Cajun Rock",
		// 8 Beat Ballad
		"Pop Ballad 1",
		"Pop Ballad 2",
		"Pop Ballad 3",
		"Rock Ballad 1",
		"Rock Ballad 2",
		"Slow Jam",
		"6/8 R&B Ballad",
		"Triplet Ballad 1",
		"Triplet Ballad 2",
		// 16 Beat Ballad
		"16 Ballad 1",
		"Dance Ballad 1",
		"Dance Ballad 2",
		"Dance Ballad 3",
		"Electro Pop",
		"16 Ballad 2",
		"Mod Pop Ballad",
		// 16 Beat Dance
		"Dance 1",
		"Dance 2",
		"Dance 3",
		"Disco",
		"Techno 1",
		"Techno 2",
		// 16 Beat Swing
		"16 Shuffle 1",
		"16 Shuffle 2",
		"16 Shuffle 3",
		"Acid Jazz 2",
		"Acid Jazz 3",
		"New Jack Swing",
		"Modern Dance",
		"Indie Pop 3",
		// 8 Beat Swing
		"Swing Beat",
		"Motown",
		"Country 2 Beat",
		"Boogie",
		// Triplet
		"8 Shuffle 1",
		"8 Shuffle 2",
		"8 Shuffle 3",
		"Dance Shuffle",
		"Triplet 1",
		"Triplet 2",
		"Triplet Rock",
		"Reggae",
		// Jazz
		"H.H. Swing",
		"Ride Swing",
		"Fast 4 Beat",
		"Afro Cuban",
		"Jazz Bossa",
		"Jazz Waltz",
		"5/4 Swing",
		// Latin / Traditional
		"H.H. Bossa Nova",
		"Ride Bossa Nova",
		"Beguine",
		"Rhumba",
		"Cha Cha",
		"Mambo",
		"Samba",
		"Sala",
		"Merenge",
		"Tango",
		"Habanera",
		"Waltz",
		"Ragtime",
		"March",
		"6/8 March",
	},
	"ambienceType": {
		"Natural",
		"Small Room",
		"Medium Room",
		"Large Room",
		"Studio",
		"Wood Studio",
		"Mellow Lounge",
		"Bright Lounge",
		"Live Stage",
		"Echo",
	},
	"reverbOnOff": {
		"Off",
		"On",
	},
	"effectsOnOff": {
		"Off",
		"On",
	},
	"reverbType": {
		"Room",
		"Lounge",
		"Small Hall",
		"Concert Hall",
		"Live Hall",
		"Cathedral",
	},
	"effectsType": {
		"Mono Delay",
		"Ping Delay",
		"Triple Delay",
		"Chorus",
		"Classic Chorus",
		"Ensemble",
		"Tremolo",
		"Classic Tremolo",
		"Vibrato Tremolo",
		"Auto Pan",
		"Classic Auto Pan",
		"Phaser",
		"Classic Phaser",
		"Rotary 1",
		"Rotary 2",
		"Rotary 3",
		"Rotary 4",
		"Rotary 5",
	},
	"smartModeVt": {
		"Off",
		"Noiseless",
		"Deep Resonance",
		"Light Resonance",
		"Soft",
		"Brilliant",
		"Clean",
		"Full",
		"Dark",
		"Rich",
		"Classical",
	},
	"touchCurve": {
		"Light+",
		"Light",
		"Normal",
		"Heavy",
		"Heavy+",
		"Off",
		"User",
	},
	"voicing": {
		"Normal",
		"Mellow 1",
		"Mellow 2",
		"Dynamic",
		"Bright 1",
		"Bright 2",
		"User",
		"User Voicing",
	},
	"topboard": {
		"Open 3",
		"Open 2",
		"Open 1",
		"Closed",
	},
	"stretchTuning": {
		"Off",
		"Normal",
		"Wide",
		"User",
	},
	"temperament": {
		"Equal",
		"Pure Major/Pure Minor",
		"Pythagorean",
		"Meantone",
		"Werckmeister",
		"Kirnberger",
		"User",
	},
	"keyVolume": {
		"Normal",
		"High Damping",
		"Low Damping",
		"High & Low Damping",
		"Center Damping",
		"User",
	},
	"shsMode": {
		"Off",
		"Forward",
		"Normal",
		"Wide",
	},
	"phonesType": {
		"Normal",
		"Open",
		"Semi-open",
		"Closed",
		"Inner-ear",
		"Canal",
	},
	"UsbThumbDrivePresence": {
		"unplugged",
		"plugged",
	},
	"phonesPresence": {
		"unplugged",
		"plugged",
	},
	"toneControl": {
		"Off",
		"Brilliance",
		"Loudness",
		"Bass Boost",
		"Treble Boost",
		"Mid Cut",
		"User",
	},
	"userToneControl": {
		"low dB",
		"mid-low freqency",
		"mid-low dB",
		"mid-high frequency",
		"mid-high dB",
		"high frequency",
	},
	"speakerVolume": {
		"Low",
		"Normal",
	},
	"phonesVolume": {
		"Normal",
		"High",
	},
	"wallEq": {
		"Off",
		"On",
	},
	"autoPowerOff": {

		"Off",
		"15 min",
		"60 min",
		"120 min",
	},

	"fileExt": {
		2: " (dir)",
		6: ".KSO",
		7: ".MID",
		8: ".MP3",
		9: ".WAV",
	},
	"emptiness": { // of various songs
		"empty",
		"used",
	},
	"mutedness": { // of various midi channels
		"muted",
		"unmuted",
	},
	"bluetoothMidi": {
		"Off",
		"On",
	},
	"bluetoothAudio": {
		"Off",
		"On",
	},
}

func addDuplicateNames() {
	names["single"] = names["instrumentSound"]
	names["dual1"] = names["instrumentSound"]
	names["dual2"] = names["instrumentSound"]
	names["split1"] = names["instrumentSound"]
	names["split2"] = names["instrumentSound"]
	names["4hands1"] = names["instrumentSound"]
	names["4hands2"] = names["instrumentSound"]
}

var tempi []uint16 = []uint16{
	0,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 42, 44, 45, 47, 50, 52,
	55, 58, 60, 63, 65, 68, 70, 72, 75, 78, 80, 83, 86, 90, 93, 96, 100,
	104, 108, 112, 116, 120, 125, 130, 136, 142, 148, 154, 160, 167, 174,
	180, 188, 196, 204, 212, 220, 230, 238, 248, 258, 269, 280, 291, 303,
	315, 328, 341, 355, 370, 384, 400,
}
